title: sloanelybutsurely.com
email: sloane@sloanelybutsurely.com
description: >- # this means to ignore newlines until "baseurl:"
  sloane's own little slice of the web. she has all sorts of stuff in here!
  come take a gander.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sloanelybutsurely.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sloanelybutsurely
locale: en
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - .jj/
  - wrangler.toml
  - mise.toml
  - README.md
  - "**/README.md"
